from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='SiteSettings',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('site_name',models.CharField(default='Seid Digital Platform',max_length=120)),('tagline',models.CharField(default='Technology • Cybersecurity • AI • Automation • Management',max_length=255)),('logo',models.ImageField(blank=True,upload_to='branding/')),('favicon',models.ImageField(blank=True,upload_to='branding/')),('primary_color',models.CharField(default='#6d5dfc',max_length=20)),('dark_mode_default',models.BooleanField(default=True)),('ai_enabled',models.BooleanField(default=True)),('blog_enabled',models.BooleanField(default=True)),('comments_enabled',models.BooleanField(default=False)),('registration_enabled',models.BooleanField(default=False)),('maintenance_mode',models.BooleanField(default=False)),('telegram_enabled',models.BooleanField(default=False)),('github_enabled',models.BooleanField(default=False)),('analytics_enabled',models.BooleanField(default=True)),('meta_description',models.TextField(blank=True)),('footer_text',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True))]),
      migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('headline',models.CharField(max_length=255)),('bio',models.TextField()),('photo',models.ImageField(blank=True,upload_to='profile/')),('cv',models.FileField(blank=True,upload_to='cv/')),('email',models.EmailField(blank=True,max_length=254)),('phone',models.CharField(blank=True,max_length=50)),('location',models.CharField(blank=True,max_length=120)),('github',models.URLField(blank=True)),('linkedin',models.URLField(blank=True)),('telegram',models.URLField(blank=True))]),
      migrations.CreateModel(name='Skill',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('category',models.CharField(blank=True,max_length=100)),('level',models.PositiveIntegerField(default=80)),('icon',models.CharField(blank=True,max_length=80)),('order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Project',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('slug',models.SlugField(blank=True,unique=True)),('summary',models.CharField(max_length=300)),('description',models.TextField()),('image',models.ImageField(blank=True,upload_to='projects/')),('technologies',models.CharField(blank=True,max_length=500)),('demo_url',models.URLField(blank=True)),('source_url',models.URLField(blank=True)),('featured',models.BooleanField(default=False)),('published',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='Certificate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('issuer',models.CharField(max_length=180)),('issue_date',models.DateField(blank=True,null=True)),('credential_url',models.URLField(blank=True)),('file',models.FileField(blank=True,upload_to='certificates/')),('featured',models.BooleanField(default=False))]),
      migrations.CreateModel(name='Experience',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(max_length=180)),('organization',models.CharField(max_length=180)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('current',models.BooleanField(default=False)),('description',models.TextField())]),
      migrations.CreateModel(name='Page',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('content',models.TextField(blank=True)),('published',models.BooleanField(default=True)),('menu',models.BooleanField(default=False)),('order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Post',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200)),('slug',models.SlugField(blank=True,unique=True)),('post_type',models.CharField(choices=[('text','Text'),('photo','Photo'),('gallery','Gallery'),('video','Video'),('document','Document'),('link','Link'),('announcement','Announcement')],default='text',max_length=30)),('body',models.TextField(blank=True)),('image',models.ImageField(blank=True,upload_to='posts/')),('video_url',models.URLField(blank=True)),('external_url',models.URLField(blank=True)),('document',models.FileField(blank=True,upload_to='documents/')),('locations',models.JSONField(blank=True,default=list)),('status',models.CharField(choices=[('draft','Draft'),('review','Review'),('scheduled','Scheduled'),('published','Published'),('archived','Archived')],default='draft',max_length=20)),('publish_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('author',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='LegalPage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('content',models.TextField()),('published',models.BooleanField(default=True)),('updated_at',models.DateTimeField(auto_now=True))]),
      migrations.CreateModel(name='ContactMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('subject',models.CharField(max_length=200)),('message',models.TextField()),('read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='Appointment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('date',models.DateTimeField()),('topic',models.CharField(max_length=200)),('notes',models.TextField(blank=True)),('status',models.CharField(choices=[('pending','Pending'),('confirmed','Confirmed'),('cancelled','Cancelled')],default='pending',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='AutomationRule',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('enabled',models.BooleanField(default=True)),('event',models.CharField(max_length=80)),('action',models.CharField(max_length=80)),('config',models.JSONField(blank=True,default=dict)),('last_run',models.DateTimeField(blank=True,null=True))]),
      migrations.CreateModel(name='ActivityLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=255)),('path',models.CharField(blank=True,max_length=500)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
    ]
