from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies=[('core','0001_initial')]
    operations=[
      migrations.AddField('SiteSettings','created_at',models.DateTimeField(auto_now_add=True,null=True)),
      migrations.AddField('SiteSettings','accent_color',models.CharField(default='#00d4ff',max_length=20)),
      migrations.AddField('SiteSettings','appointments_enabled',models.BooleanField(default=True)),
      migrations.AddField('SiteSettings','newsletter_enabled',models.BooleanField(default=False)),
      migrations.AddField('SiteSettings','meta_title',models.CharField(blank=True,max_length=180)),
      migrations.AddField('SiteSettings','meta_keywords',models.CharField(blank=True,max_length=500)),
      migrations.AddField('SiteSettings','og_image',models.ImageField(blank=True,upload_to='seo/')),
      migrations.AddField('SiteSettings','email',models.EmailField(blank=True,max_length=254)), migrations.AddField('SiteSettings','phone',models.CharField(blank=True,max_length=60)), migrations.AddField('SiteSettings','location',models.CharField(blank=True,max_length=160)),
      migrations.AddField('SiteSettings','github_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','linkedin_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','telegram_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','facebook_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','instagram_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','youtube_url',models.URLField(blank=True)), migrations.AddField('SiteSettings','maintenance_message',models.TextField(blank=True,default='We are upgrading the platform. Please check back soon.')),
      migrations.AddField('Profile','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('Profile','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Profile','availability',models.CharField(blank=True,max_length=120)), migrations.AddField('Profile','website',models.URLField(blank=True)),
      migrations.AddField('Skill','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('Skill','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Skill','featured',models.BooleanField(default=True)),
      migrations.AddField('Project','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Project','github_repo',models.CharField(blank=True,max_length=220)), migrations.AddField('Project','order',models.PositiveIntegerField(default=0)),
      migrations.AddField('Certificate','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('Certificate','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Certificate','credential_id',models.CharField(blank=True,max_length=180)), migrations.AddField('Certificate','order',models.PositiveIntegerField(default=0)),
      migrations.AddField('Experience','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('Experience','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Experience','location',models.CharField(blank=True,max_length=150)),
      migrations.AddField('Page','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('Page','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Page','seo_title',models.CharField(blank=True,max_length=180)), migrations.AddField('Page','seo_description',models.TextField(blank=True)),
      migrations.AddField('Post','seo_title',models.CharField(blank=True,max_length=180)), migrations.AddField('Post','seo_description',models.TextField(blank=True)), migrations.AddField('Post','tags',models.CharField(blank=True,max_length=500)), migrations.AddField('Post','gallery',models.JSONField(blank=True,default=list)), migrations.AddField('Post','custom_locations',models.CharField(blank=True,max_length=500)),
      migrations.AddField('LegalPage','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('LegalPage','seo_description',models.TextField(blank=True)),
      migrations.AddField('ContactMessage','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('ContactMessage','replied',models.BooleanField(default=False)), migrations.AddField('ContactMessage','ip_address',models.GenericIPAddressField(blank=True,null=True)),
      migrations.AddField('Appointment','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('Appointment','phone',models.CharField(blank=True,max_length=60)),
      migrations.AddField('AutomationRule','created_at',models.DateTimeField(auto_now_add=True,null=True)), migrations.AddField('AutomationRule','updated_at',models.DateTimeField(auto_now=True,null=True)), migrations.AddField('AutomationRule','last_error',models.TextField(blank=True)),
      migrations.AddField('ActivityLog','metadata',models.JSONField(blank=True,default=dict)),
      migrations.CreateModel(name='Service',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('slug',models.SlugField(blank=True,unique=True)),('summary',models.CharField(max_length=300)),('description',models.TextField()),('icon',models.CharField(blank=True,max_length=80)),('image',models.ImageField(blank=True,upload_to='services/')),('featured',models.BooleanField(default=True)),('published',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Education',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('institution',models.CharField(max_length=180)),('degree',models.CharField(max_length=180)),('field',models.CharField(blank=True,max_length=180)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('current',models.BooleanField(default=False)),('description',models.TextField(blank=True))]),
      migrations.CreateModel(name='Testimonial',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('role',models.CharField(blank=True,max_length=180)),('company',models.CharField(blank=True,max_length=180)),('quote',models.TextField()),('photo',models.ImageField(blank=True,upload_to='testimonials/')),('published',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Section',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('section_type',models.CharField(choices=[('hero','Hero'),('about','About'),('skills','Skills'),('projects','Projects'),('services','Services'),('experience','Experience'),('education','Education'),('certificates','Certificates'),('testimonials','Testimonials'),('posts','Posts'),('contact','Contact'),('custom','Custom')],max_length=30)),('enabled',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0)),('title',models.CharField(blank=True,max_length=180)),('subtitle',models.CharField(blank=True,max_length=300)),('content',models.TextField(blank=True)),('settings',models.JSONField(blank=True,default=dict))]),
      migrations.CreateModel(name='NewsletterSubscriber',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('email',models.EmailField(max_length=254,unique=True)),('active',models.BooleanField(default=True)),('token',models.CharField(blank=True,max_length=80))]),
      migrations.CreateModel(name='MediaAsset',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('file',models.FileField(upload_to='library/')),('alt_text',models.CharField(blank=True,max_length=255)),('caption',models.CharField(blank=True,max_length=500)),('folder',models.CharField(default='general',max_length=120)),('uploaded_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='SocialLink',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=80)),('url',models.URLField()),('icon',models.CharField(blank=True,max_length=80)),('enabled',models.BooleanField(default=True)),('order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Integration',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('provider',models.CharField(choices=[('github','GitHub'),('telegram','Telegram'),('gemini','Gemini AI'),('openai','OpenAI'),('smtp','Email/SMTP'),('analytics','Analytics'),('webhook','Webhook')],max_length=30,unique=True)),('enabled',models.BooleanField(default=False)),('public_identifier',models.CharField(blank=True,max_length=255)),('settings',models.JSONField(blank=True,default=dict)),('last_sync',models.DateTimeField(blank=True,null=True)),('last_error',models.TextField(blank=True))]),
      migrations.CreateModel(name='AnalyticsEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('event_type',models.CharField(choices=[('pageview','Page View'),('download','Download'),('contact','Contact'),('ai','AI Question'),('click','Click')],max_length=30)),('path',models.CharField(blank=True,max_length=500)),('referrer',models.CharField(blank=True,max_length=500)),('user_agent',models.TextField(blank=True)),('session_key',models.CharField(blank=True,max_length=100)),('ip_hash',models.CharField(blank=True,max_length=128)),('metadata',models.JSONField(blank=True,default=dict))]),
      migrations.CreateModel(name='AIConversation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('session_key',models.CharField(max_length=100)),('question',models.TextField()),('answer',models.TextField()),('provider',models.CharField(blank=True,max_length=40)),('success',models.BooleanField(default=True))]),
      migrations.CreateModel(name='WebhookEndpoint',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('url',models.URLField()),('secret',models.CharField(blank=True,max_length=255)),('enabled',models.BooleanField(default=True)),('events',models.JSONField(blank=True,default=list)),('last_sent',models.DateTimeField(blank=True,null=True)),('last_error',models.TextField(blank=True))]),
    ]
